version: '2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - '/Users/dan/workspace/personal/codes/dockstation-files:/var/jenkins_home'
    ports:
      - '8080:8080'
      - '50000:50000'
